import type { RhwLanguage } from "../context/RhwAppContext";

const COPY = {
  English: {
    home:"Home", care:"Care", sos:"SOS", messages:"Messages", profile:"Profile",
    goodMorning:"Good morning", goodAfternoon:"Good afternoon", goodEvening:"Good evening",
    ready:"Ready for today's community care.", professionalStatus:"Professional status",
    active:"Active", workspace:"Today's workspace", careRequests:"Care requests",
    activeSos:"Active SOS", conversations:"Conversations", assignedToMe:"Assigned to me",
    workAssignment:"Your work assignment", facility:"Facility", catchment:"Catchment area",
    district:"District", training:"Training level", notSet:"Not set", refresh:"Refresh",
    all:"All", mine:"Mine", unassigned:"Unassigned", urgent:"Urgent", activeOnly:"Active",
    critical:"Critical", noCare:"No care requests are currently within your 3 km response radius.",
    noSos:"No SOS alerts are currently within your 3 km response radius.",
    noConversations:"No conversations are currently available to this account.",
    loadFailed:"Could not load data",
    responderAccess:"Unassigned Care and SOS items appear only when the patient location is within 3 km of your registered RHW location. Cases already assigned to you remain visible.",
    takeCase:"Take case", startCare:"Start care", complete:"Complete", acknowledge:"Acknowledge",
    responding:"Responding", closeAlert:"Close alert", patient:"Patient", priority:"Priority",
    status:"Status", description:"Description", location:"Location", assigned:"Assigned",
    voiceAttached:"Original voice note attached",
    voicePermission:"The recording remains unchanged. Playback depends on responder Storage permission.",
    typeMessage:"Type a message...", send:"Send",
    noMessages:"No messages in this conversation yet.", messageFailed:"Message could not be sent.",
    professionalProfile:"RHW profile", workerNumber:"Worker number", phone:"Phone",
    province:"Province", preferredLanguage:"Preferred language", languageSaved:"Language updated.",
    updateFailed:"Could not update profile.", signOut:"Sign out", signOutFailed:"Unable to sign out.",
    accessLimited:"Responder access limited", realData:"Live Appwrite data",
  },
  Shona: {
    home:"Kumba", care:"Rubatsiro", sos:"SOS", messages:"Mameseji", profile:"Nhoroondo",
    goodMorning:"Mangwanani", goodAfternoon:"Masikati", goodEvening:"Manheru",
    ready:"Wagadzirira basa rehutano renharaunda nhasi.", professionalStatus:"Mamiriro ebasa",
    active:"Inoshanda", workspace:"Basa ranhasi", careRequests:"Zvikumbiro zvehutano",
    activeSos:"SOS dziri kushanda", conversations:"Hurukuro", assignedToMe:"Zvandakapiwa",
    workAssignment:"Basa rawakapihwa", facility:"Nzvimbo yehutano", catchment:"Nzvimbo yaunoshandira",
    district:"Ruwa", training:"Chikamu chekudzidziswa", notSet:"Hazvina kuiswa", refresh:"Dzokorora",
    all:"Zvese", mine:"Zvangu", unassigned:"Zvisina kupihwa", urgent:"Zvekukurumidza",
    activeOnly:"Zviri kushanda", critical:"Zvakanyanya",
    noCare:"Hapana zvikumbiro zvehutano zviri mukati me3 km yenzvimbo yako yekupindura.",
    noSos:"Hapana SOS dziri mukati me3 km yenzvimbo yako yekupindura.",
    noConversations:"Hapana hurukuro dziri kuwanikwa paaccount iyi.", loadFailed:"Data harina kukwanisa kuverengwa",
    responderAccess:"Zvikumbiro zvisina kupihwa neSOS zvinoonekwa chete kana murwere ari mukati me3 km yenzvimbo yakanyoreswa yeRHW. Nyaya dzawakapiwa dzinoramba dzichionekwa.",
    takeCase:"Tora nyaya", startCare:"Tanga rubatsiro", complete:"Pedzisa", acknowledge:"Gamuchira",
    responding:"Ndiri kupindura", closeAlert:"Vhara SOS", patient:"Murwere", priority:"Kukurumidza",
    status:"Mamiriro", description:"Tsananguro", location:"Nzvimbo", assigned:"Yakapiwa",
    voiceAttached:"Voice note yepakutanga iripo",
    voicePermission:"Recording haina kuchinjwa. Playback inoda mvumo yeStorage yemupinduri.",
    typeMessage:"Nyora meseji...", send:"Tumira", noMessages:"Hapana mameseji muhurukuro iyi.",
    messageFailed:"Meseji yatadza kutumirwa.", professionalProfile:"Nhoroondo yeRHW",
    workerNumber:"Nhamba yemushandi", phone:"Foni", province:"Dunhu",
    preferredLanguage:"Mutauro waunoda", languageSaved:"Mutauro wachinjwa.",
    updateFailed:"Nhoroondo yatadza kugadziriswa.", signOut:"Buda", signOutFailed:"Kubuda kwatadza.",
    accessLimited:"Mvumo yemupinduri ishoma", realData:"Data chaiyo yeAppwrite",
  },
  isiNdebele: {
    home:"Ikhaya", care:"Ukunakekelwa", sos:"SOS", messages:"Imilayezo", profile:"Iphrofayili",
    goodMorning:"Livukile", goodAfternoon:"Litshonile", goodEvening:"Litshonile",
    ready:"Ulungele umsebenzi wezempilo womphakathi wanamuhla.", professionalStatus:"Isimo somsebenzi",
    active:"Iyasebenza", workspace:"Umsebenzi wanamuhla", careRequests:"Izicelo zokunakekelwa",
    activeSos:"Ama-SOS asebenzayo", conversations:"Izingxoxo", assignedToMe:"Okwami",
    workAssignment:"Umsebenzi owabelweyo", facility:"Indawo yezempilo", catchment:"Indawo oyisebenzelayo",
    district:"Isigaba", training:"Izinga lokuqeqeshwa", notSet:"Akufakwanga", refresh:"Vuselela",
    all:"Konke", mine:"Okwami", unassigned:"Akukabelwa", urgent:"Okuphuthumayo",
    activeOnly:"Okusebenzayo", critical:"Okubucayi",
    noCare:"Akula zicelo zokunakekelwa eziphakathi kwe3 km yendawo yakho yokuphendula.",
    noSos:"Akula zaziso zeSOS eziphakathi kwe3 km yendawo yakho yokuphendula.",
    noConversations:"Akula zingxoxo ezitholakalayo kule account.", loadFailed:"Idatha yehlulekile ukulayishwa",
    responderAccess:"Izicelo ezingakabelwa leSOS zibonakala kuphela nxa isiguli siphakathi kwe3 km yendawo ebhaliswe yeRHW. Amacala asebelwe wena ahlala ebonakala.",
    takeCase:"Thatha icala", startCare:"Qala ukunakekela", complete:"Qedela", acknowledge:"Yamukela",
    responding:"Ngiyaphendula", closeAlert:"Vala iSOS", patient:"Isiguli", priority:"Ukuphuthuma",
    status:"Isimo", description:"Incazelo", location:"Indawo", assigned:"Kwabelwe",
    voiceAttached:"I-voice note yokuqala ikhona",
    voicePermission:"Ukurekhoda akuguqulwanga. Ukudlala kudinga imvumo yeStorage yomphenduli.",
    typeMessage:"Bhala umlayezo...", send:"Thumela", noMessages:"Akula milayezo kule ngxoxo.",
    messageFailed:"Umlayezo wehlulekile ukuthunyelwa.", professionalProfile:"Iphrofayili yeRHW",
    workerNumber:"Inombolo yesisebenzi", phone:"Ifoni", province:"Isifundazwe",
    preferredLanguage:"Ulimi oluthandayo", languageSaved:"Ulimi lugcinwe.",
    updateFailed:"Iphrofayili yehlulekile ukugcinwa.", signOut:"Phuma", signOutFailed:"Ukuphuma kwehlulekile.",
    accessLimited:"Imvumo yomphenduli ilinganiselwe", realData:"Idatha yeAppwrite ephilayo",
  },
} as const;

export type RhwCopyKey = keyof typeof COPY.English;

export function rhwT(language: RhwLanguage, key: RhwCopyKey) {
  return COPY[language]?.[key] ?? COPY.English[key];
}
